#!/usr/bin/env bash
# Pick the first region that actually has capacity for the whole topology, and
# write the choice where terraform will pick it up.
#
# The capacity probe this uses already existed, but it only ever aborted and
# asked a human to "try another region" - which made region selection a manual
# decision and the reason a reproduction could stall on someone else's judgment.
# This removes that step.
#
# The history is worth knowing: on 2026-07-29 us-east-1 was out of
# r8id.8xlarge capacity REGION-WIDE, not just in one zone - no AZ combination
# would have worked - and finding that out cost hours of hung RunInstances
# calls. That is what this script exists to make cheap.
#
# IMPORTANT for reproducibility: the region is part of a result's fingerprint.
# Landing in a different region than the published runs may make numbers
# incomparable (different hardware generations behind the same instance name,
# different network topology). This script therefore RECORDS its choice and
# warns when it is not the region the published results used.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib-capacity.sh
. "$HERE/lib-capacity.sh"

TF_DIR="${TF_DIR:-$HERE/../terraform}"
TFVARS="${TFVARS:-$TF_DIR/r8id-8xl-wasm-single-az.tfvars}"
# Ordered preference. First region with capacity for every needed pair wins.
REGIONS="${REGIONS:-us-east-2 us-east-1 us-west-2 eu-west-1}"
# The region the published measurements were taken in.
PUBLISHED_REGION="${PUBLISHED_REGION:-us-east-2}"
OVERLAY="${OVERLAY:-$TF_DIR/region.auto.tfvars}"

[ -f "$TFVARS" ] || { echo "no tfvars at $TFVARS" >&2; exit 1; }

BROKER_COUNT=$(tfvar "$TFVARS" broker_count)
CLIENT_COUNT=$(tfvar "$TFVARS" client_count)
BROKER_ITYPE=$(tfvar "$TFVARS" broker_instance_type)
CLIENT_ITYPE=$(tfvar "$TFVARS" client_instance_type)
NAZS=$(tfvar_list_len "$TFVARS" azs)
[ "${NAZS:-0}" -ge 1 ] || { echo "could not read azs from $TFVARS" >&2; exit 1; }

echo "topology from $(basename "$TFVARS"):"
echo "  ${BROKER_COUNT} x ${BROKER_ITYPE} brokers, ${CLIENT_COUNT} x ${CLIENT_ITYPE} clients, ${NAZS} AZ(s)"
echo "candidate regions (in order): $REGIONS"
echo ""

# The AZs the tfvars already names, i.e. the ones the published runs used. When
# the candidate region IS that region, probe THOSE AZs rather than whichever
# come first alphabetically - otherwise a default reproduction silently lands in
# a different availability zone than the published numbers, which is the same
# comparability problem as a different region and was exactly what the first cut
# of this script did (picked us-east-2a when the results were from us-east-2c).
TFVARS_REGION=$(tfvar "$TFVARS" region)
TFVARS_AZS=$(grep -oP '^\s*azs\s*=\s*\K\[.*\]' "$TFVARS" 2>/dev/null | head -1 \
             | tr -d '[]"' | tr ',' ' ')

CHOSEN=""; CHOSEN_AZS=""
declare -A WHY
for region in $REGIONS; do
  echo "--- probing $region ---"
  if [ "$region" = "$TFVARS_REGION" ] && [ -n "$TFVARS_AZS" ]; then
    azs="$TFVARS_AZS"
    echo "    using the AZ(s) this topology already names: $azs"
  else
    azs=$(region_azs "$region" "$NAZS" | tr '\n' ' ')
  fi
  n_have=$(echo $azs | wc -w)
  if [ "$n_have" -lt "$NAZS" ]; then
    WHY[$region]="only $n_have usable AZ(s), need $NAZS"
    echo "    -> $region has only $n_have usable AZ(s), trying next"
    continue
  fi
  fail=0
  while read -r az itype; do
    [ -z "$az" ] && continue
    if capacity_available "$region" "$az" "$itype"; then echo "    OK   $itype in $az"
    else echo "    FAIL $itype in $az"; fail=1; fi
  done < <(needed_pairs "$NAZS" "$BROKER_COUNT" "$BROKER_ITYPE" \
             "$CLIENT_COUNT" "$CLIENT_ITYPE" $azs)
  if [ "$fail" = 0 ]; then
    CHOSEN="$region"; CHOSEN_AZS="$azs"
    echo "    -> $region has capacity for the whole topology"
    break
  fi
  WHY[$region]="at least one (AZ, instance type) pair unavailable"
  echo "    -> $region insufficient, trying next"
done

if [ -z "$CHOSEN" ]; then
  echo "" >&2
  echo "ABORT: no candidate region has capacity for this topology right now." >&2
  for r in $REGIONS; do echo "  $r: ${WHY[$r]:-unknown}" >&2; done
  echo "" >&2
  echo "Nothing has been provisioned. Options: wait and retry, widen REGIONS," >&2
  echo "or reduce client_count (see README on how consumer count drives it)." >&2
  exit 1
fi

AZ_LIST=$(for a in $CHOSEN_AZS; do printf '"%s", ' "$a"; done); AZ_LIST="[${AZ_LIST%, }]"

cat > "$OVERLAY" <<EOF
# GENERATED by scripts/select-region.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) - do not edit.
# Chosen because it was the first region in REGIONS="$REGIONS"
# with confirmed capacity for every (AZ, instance type) pair this topology needs.
# Terraform loads *.auto.tfvars automatically, after the explicit -var-file, so
# these win.
region = "$CHOSEN"
azs    = $AZ_LIST
EOF

echo ""
echo "wrote $OVERLAY:"
sed 's/^/    /' "$OVERLAY"

if [ -n "$TFVARS_AZS" ] && [ "$CHOSEN_AZS" != "$TFVARS_AZS" ]; then
  echo ""
  echo "WARNING: availability zone(s) changed from '$TFVARS_AZS' to" >&2
  echo "         '$CHOSEN_AZS'. Same instance name in a different zone can be" >&2
  echo "         different hardware, so record the AZ with any result." >&2
fi
if [ "$CHOSEN" != "$PUBLISHED_REGION" ]; then
  echo ""
  echo "WARNING: selected $CHOSEN, but the published results were measured in" >&2
  echo "         $PUBLISHED_REGION. Latencies may not be directly comparable -" >&2
  echo "         same instance name can mean different hardware, and network" >&2
  echo "         topology differs. Record the region alongside any result." >&2
fi
echo "REGION_SELECTED $CHOSEN"
