#!/usr/bin/env bash
# Derive how many client instances the traditional arm needs from the consumer
# ladder, and write it into a tfvars overlay.
#
# WHY THIS IS NOT LEFT TO THE OPERATOR: under-provisioning here does not fail
# loudly, it produces a plausible-looking latency that is actually the load
# generator running out of CPU. Measured on 2026-09-03 with 499 consumer groups
# and loadgen on ONE c5n.9xlarge: every existing gate passed - attempted_ratio
# 99.99%, client_bound false, lag never grew, 29,997 of 29,997 receipts - and
# e2e p50 read 7,629us. send_lateness p99 was 2,486us against a 1,000us pacing
# interval, i.e. the generator was 2.5 slots late at the tail, and an unknown
# share of that 7,629us was client-side queueing.
#
# THE MEASURED BUDGET, same instance type:
#   49 background groups + loadgen co-located -> pacing HELD  (p99   544us)
#   99 background groups + loadgen co-located -> pacing LOST  (p99 1,003us)
# So ~84 groups per dedicated instance is comfortably inside the envelope even
# before crediting the removal of loadgen's own share, and loadgen gets an
# instance to itself so its pacing is never the thing that degrades.
#
# Roles: client0 = loadgen only. client1 = the external matcher. client2..N =
# background consumer groups, evenly sharded.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${TF_DIR:-$HERE/../terraform}"
OVERLAY="${OVERLAY:-$TF_DIR/clients.auto.tfvars}"

# Consumer counts the traditional arm will sweep. loadgen is one of them.
EXTERNAL_LADDER="${EXTERNAL_LADDER:-1 10 50 500}"
GROUPS_PER_INSTANCE="${GROUPS_PER_INSTANCE:-84}"

max=0
for n in $EXTERNAL_LADDER; do
  case "$n" in ''|*[!0-9]*) echo "EXTERNAL_LADDER must be integers, got '$n'" >&2; exit 1 ;; esac
  [ "$n" -gt "$max" ] && max="$n"
done
[ "$max" -ge 1 ] || { echo "EXTERNAL_LADDER must contain at least one level >= 1" >&2; exit 1; }

# loadgen is the measured consumer, so it accounts for one of the level's
# consumers; the rest are background groups.
background=$(( max - 1 ))
if [ "$background" -le 0 ]; then
  fanout_hosts=0
else
  fanout_hosts=$(( (background + GROUPS_PER_INSTANCE - 1) / GROUPS_PER_INSTANCE ))
fi
# +1 loadgen, +1 external matcher. Both need their own instance: co-locating
# the matcher with loadgen would put the thing being measured on the same CPU
# as the thing measuring it.
client_count=$(( 2 + fanout_hosts ))

cat > "$OVERLAY" <<EOF
# GENERATED by scripts/size-clients.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) - do not edit.
#
# EXTERNAL_LADDER="$EXTERNAL_LADDER" -> peak $max consumers
#   1 instance  loadgen (measured consumer, nothing co-located)
#   1 instance  external matcher (cmd/wasm-client)
#   $fanout_hosts instance(s) x <=$GROUPS_PER_INSTANCE background groups = $background groups
client_count = $client_count
EOF

echo "peak consumers        : $max"
echo "background groups     : $background"
echo "groups per instance   : $GROUPS_PER_INSTANCE (measured safe; 99 + loadgen was not)"
echo "fanout instances      : $fanout_hosts"
echo "client_count          : $client_count  (loadgen + matcher + fanout)"
echo "wrote                 : $OVERLAY"
echo "CLIENT_COUNT $client_count"
